# 使用yaml做配置项
# 数据库配置项
db:
  mysql:
    dbname: "blog_go"
    password: "123456"
    username: "root"
    port: 3307
    host: "127.0.0.1"
log:
  # 默认路径是运行程序的目录
  #  logDirector: ./logging
  logInfoFilename: info.log
  logMaxSize: 10
  logMaxBackups: 5
  logMaxAge: 10
  logLevel: info

